[testenv]
usedevelop = True
deps =
    -rrequirements.txt
    coverage
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    # 1. Run the tests and gather data
    coverage run --source=ImageHorizonLibrary -m unittest discover -s tests/utest
    # 2. Display the summary in the console
    coverage report -m
    # 3. (Optional) Create an HTML report for manual inspection
    coverage html
